### ISSUE TITLE
API calls from the server require an appsecret_proof argument.

### ISSUE THREAD

**Issue by ZaidPathan** [fbsamples/account-kit-samples-for-ios#5]
Giving this error even if user is logged in.
Which method developer needs to call to pass access_token, app_secret in Account Kit?
Disabling "Require app secret" in Account Kit settings does the trick, but what about security?

**Comment by olgaikuznetsova** [comment]
Please note that this is the Github page for our samples project, not for the whole of AccountKit. Please file bugs/issues with AccountKit in our developer portal: https://developers.facebook.com/bugs/?tag_ids=1679169675664406

Could you file a bug there with what the error is and the steps that you took to get to that spot - it didn't show up in the issue here. You should also specify the platform you're using (Android, iOS, JS) and login type (Phone, email).
