### ISSUE TITLE
Country Code Configuring not work

### ISSUE THREAD

**Issue by Hokila** [fbsamples/account-kit-samples-for-ios#6]
Hi,
I follow 
https://developers.facebook.com/docs/accountkit/ios/customizingcodes
tutorial configuration SMS restriction,

my code at
https://github.com/Hokila/account-kit-samples-for-ios
should be only left NL and US, and default set to US
but it's still show up all county code.

**Comment by olgaikuznetsova** [comment]
Thanks for also filing this in our developer portal (https://developers.facebook.com/bugs/1682997505296585/) - that's a better way to file issues with the Account Kit product - this is just the github for the sample project. 

This was an error in our documentation which we're getting fixed and will comment on the task you filed when that is complete. Meanwhile you can set the whitelist and blacklist on the controller instead of in the plist such as in this example (this is the same way as you can set the advancedUIManager on the controller - https://developers.facebook.com/docs/accountkit/ios/customizing):

loginViewController.whitelistedCountryCodes = @[@"US", @"NL", ];
loginViewController.blacklistedCountryCodes = @[@"ID"];

Thanks!
